# Generated by Django 3.1.7 on 2021-04-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pagseguro', 'Pagseguro'), ('paypal', 'Paypal'), ('deposit', 'Depósito')], default='deposit', max_length=20, verbose_name='Opção de Pagamento'),
        ),
    ]
